import {
    Alignment,
    Autoformat,
    AutoLink,
    BlockQuote,
    Bold,
    ClassicEditor,
    CodeBlock,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    Highlight,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SimpleUploadAdapter,
    SpecialCharacters,
    SpecialCharactersArrows,
    SpecialCharactersCurrency,
    SpecialCharactersEssentials,
    SpecialCharactersLatin,
    SpecialCharactersMathematical,
    SpecialCharactersText,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableCellProperties,
    TableProperties,
    TableToolbar,
    TextTransformation,
    Title,
    Underline
} from "ckeditor5";

import 'ckeditor5/ckeditor5.css';

export default class Editor extends ClassicEditor {
    static builtinPlugins = [
        Alignment,
        Autoformat,
        AutoLink,
        BlockQuote,
        Bold,
        CodeBlock,
        Essentials,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        Heading,
        Highlight,
        HorizontalLine,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        ImageInsert,
        Indent,
        IndentBlock,
        Italic,
        Link,
        LinkImage,
        List,
        ListProperties,
        MediaEmbed,
        Paragraph,
        PasteFromOffice,
        RemoveFormat,
        SimpleUploadAdapter,
        SpecialCharacters,
        SpecialCharactersArrows,
        SpecialCharactersCurrency,
        SpecialCharactersEssentials,
        SpecialCharactersLatin,
        SpecialCharactersMathematical,
        SpecialCharactersText,
        Strikethrough,
        Subscript,
        Superscript,
        Table,
        TableCellProperties,
        TableProperties,
        TableToolbar,
        TextTransformation,
        Title,
        Underline
    ];

    static defaultConfig = {
        toolbar: {
            items: [
                'undo',
                'redo',
                'removeFormat',
                '|',
                'heading',
                '|',
                'fontFamily',
                'fontSize',
                'bold',
                'italic',
                'underline',
                'strikethrough',
                'fontColor',
                'fontBackgroundColor',
                '|',
                'link',
                'insertImage',
                'mediaEmbed',
                '|',
                'alignment',
                '|',
                'bulletedList',
                'numberedList',
                'indent',
                'outdent',
                '|',
                'subscript',
                'superscript',
                '|',
                'blockQuote',
                'insertTable',
                '|',
                'highlight',
                'horizontalLine',
                '|',
                'codeBlock',
                'specialCharacters'
            ]
        },
        language: 'en',
        image: {
            resizeUnit: 'px',
            styles: [
                'alignLeft', 'alignCenter', 'alignRight'
            ],
            toolbar: [
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
                '|',
                'imageTextAlternative'
            ]
        },
        table: {
            contentToolbar: [
                'tableAlignment',
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableCellProperties',
                'tableProperties'
            ]
        },
    }
}
